name: test

on:
  - push

jobs:
  set-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v5
      - id: set-targets
        run: |
          echo "targets=$(ls -d *_route | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  test:
    name: test
    runs-on: ubuntu-latest
    needs: set-targets
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.set-targets.outputs.targets ) }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: |
          go run ${{ matrix.target }}/main.go
